name: "Run Template DApps Integration"

on:
  pull_request:
    branches: [main]
  repository_dispatch:
    types: [run-template-dapps-integration]
  workflow_dispatch:

jobs:
  run_template_dapps_integration_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup yarn
        run: npm install -g yarn

      - name: Run template integration script
        run: |
          chmod +x ./scripts/template-dapps-integration.sh
          ./scripts/template-dapps-integration.sh
        shell: bash
